### ISSUE TITLE
Meow Build Options Error

### ISSUE THREAD

**Issue by jlumsla** [OzzyCzech/mock-to-openapi#3]
I am running Node.js v20.12.2.
I am receiving the following error on execution.

file:///usr/local/lib/node_modules/mock-to-openapi/node_modules/meow/build/options.js:52
		throw new Error(errorMessages.join('\n'));
		      ^

Error: The option `alias` has been renamed to `shortFlag`. The following flags need to be updated: `--verbose`, `--write`
    at validateOptions (file:///usr/local/lib/node_modules/mock-to-openapi/node_modules/meow/build/options.js:52:9)
    at buildOptions (file:///usr/local/lib/node_modules/mock-to-openapi/node_modules/meow/build/options.js:87:2)
    at meow (file:///usr/local/lib/node_modules/mock-to-openapi/node_modules/meow/build/index.js:86:24)
    at file:///usr/local/lib/node_modules/mock-to-openapi/cli.js:9:13
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.2

**Comment by OzzyCzech** [comment]
Please download [new version](https://www.npmjs.com/package/mock-to-openapi/v/1.1.2)
